#!/usr/bin/env bash
# Run the relayer and the bridge UI.
#
# The relayer is the same binary the testnet runs, with the config `write_config` generates
# from what `make init` deployed: the same chains and routes as deploy/coprocessor.toml.example,
# with this devnet's own ids.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

need docker
need jq
need curl

# A pruned image or build tree must not be a broken devnet.
"$(dirname "${BASH_SOURCE[0]}")/10-celestia-up.sh"

has routing-ism-id || die "no routing ism; run 'make init' first"

write_config
routes="$(grep -c '^\[\[routes\]\]' "${COPROCESSOR_CONFIG}")"
say "${routes} routes in ${COPROCESSOR_CONFIG}"

mkdir -p "${STATE_DIR}/proofs" "${STATE_DIR}/logs"

# Replace anything left running, so 'make start' twice does not leave two relayers competing
# for the same route.
for pidfile in relayer ui; do
  if [ -f "${STATE_DIR}/${pidfile}.pid" ]; then
    kill "$(cat "${STATE_DIR}/${pidfile}.pid")" 2>/dev/null || true
    rm -f "${STATE_DIR}/${pidfile}.pid"
  fi
done
pkill -f "tee-hyperlane --config" 2>/dev/null || true

say "starting the relayer"
APPD="${APPD}" COLLATERAL_BIN="${COLLATERAL_BIN}" \
  "${COPROCESSOR_BIN}" --config "${COPROCESSOR_CONFIG}" > "${STATE_DIR}/logs/relayer.log" 2>&1 &
echo $! > "${STATE_DIR}/relayer.pid"
say "relayer log: ${STATE_DIR}/logs/relayer.log"

# alive <name> <pidfile> <log> - a process that died on start must not read as running.
alive() {
  sleep 5
  kill -0 "$(cat "$2")" 2>/dev/null && return 0
  tail -20 "$3" >&2
  die "$1 exited right after starting; its log is above and in $3"
}
alive relayer "${STATE_DIR}/relayer.pid" "${STATE_DIR}/logs/relayer.log"

# The UI's deployment values normally name the live testnet. The devnet mints its ids at
# genesis, so they cannot be known in advance and are written here instead.
# Empty rather than absent when an asset was not deployed: the UI reads an empty value as
# "not on this route" and hides the control, instead of offering one that cannot work.
opt() { has "$1" && load "$1" || true; }

say "pointing the UI at the devnet"
cat > "${REPO_DIR}/bridge-app/.env.local" <<ENV
# Generated by 'make start'. Delete this file to point the UI back at the live testnet.
VITE_CELESTIA_NAME=Celestia devnet
VITE_CELESTIA_CHAIN_ID=${CHAINID}
VITE_CELESTIA_DOMAIN=${CELESTIA_DOMAIN}
VITE_CELESTIA_RPC=${CELESTIA_RPC}
VITE_CELESTIA_REST=${CELESTIA_API}
VITE_CELESTIA_EXPLORER=${CELESTIA_API}
VITE_CELESTIA_MAILBOX_ID=$(load mailbox-id)
# The routing ISM, not one origin's: it is what the mailbox defaults to and what fans every
# origin out to the ISM that pins that origin's enclave.
VITE_CELESTIA_ISM_ID=$(load routing-ism-id)
VITE_CELESTIA_IGP_ID=$(load noop-hook-id)
VITE_CELESTIA_TIA_ROUTER=$(load celestia-token-id)
VITE_CELESTIA_TEEUSD_ROUTER=$(opt celestia-teeusd-token-id)
VITE_SEPOLIA_TEEUSD_ROUTER=$(opt sepolia-teeusd-router)
VITE_ARBITRUM_TEEUSD_ROUTER=$(opt arbitrum-teeusd-router)
VITE_BASE_TEEUSD_ROUTER=$(opt base-teeusd-router)
VITE_EDEN_TEEUSD_ROUTER=$(opt eden-teeusd-router)
# No proving: the destination verifies the enclave's quote directly, so the only wait is the
# origin's finality plus a block.
VITE_PROVING_SECONDS=30
ENV

say "starting the bridge UI on http://localhost:3000"
(
  cd "${REPO_DIR}/bridge-app"
  [ -d node_modules ] || npm install --silent
  VITE_DEVNET=1 npm run dev -- --port 3000 --strictPort \
    > "${STATE_DIR}/logs/ui.log" 2>&1 &
  echo $! > "${STATE_DIR}/ui.pid"
)
alive "the bridge UI" "${STATE_DIR}/ui.pid" "${STATE_DIR}/logs/ui.log"

say "devnet is running"
echo
echo "  UI        http://localhost:3000"
echo "  relayer   ${STATE_DIR}/logs/relayer.log"
echo "  chain     ${CELESTIA_RPC}"
echo
echo "'make stop' tears it down and deletes the phala instances."
