[package]
name = "tee-coprocessor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hyperlane-types.workspace = true
tree_hash = "0.10"
tee-attestation.workspace = true
tee-node.workspace = true
alloy-primitives.workspace = true

anyhow.workspace = true
base64.workspace = true
clap = { version = "4", features = ["derive"] }
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
toml = "0.8"
tendermint.workspace = true
tendermint-rpc.workspace = true
reqwest.workspace = true
sp1-sdk = { version = "=5.2.2", features = ["native-gnark"] }
dcap-qvl = { version = "=0.5.3", default-features = false, features = ["std", "rustcrypto", "default-x509", "report"] }
tendermint-light-client-verifier.workspace = true
helios-consensus-core.workspace = true
axum.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "tee-hyperlane"
path = "src/main.rs"
