[package]
name = "tee-coprocessor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hyperlane-types.workspace = true
tree_hash = "0.10"
celestia-types.workspace = true
tee-node.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true

anyhow.workspace = true
base64.workspace = true
clap = { version = "4", features = ["derive"] }
hex.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time", "process"] }
async-trait = "0.1"
tempfile = "3"
toml = "0.8"
tendermint.workspace = true
tendermint-rpc.workspace = true
reqwest.workspace = true
dcap-qvl = { version = "=0.5.3", default-features = false, features = ["std", "rustcrypto", "default-x509", "report"] }
tendermint-light-client-verifier.workspace = true
helios-consensus-core.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "tee-hyperlane"
path = "src/main.rs"

[dev-dependencies]
filetime = "0.2"
